### ISSUE TITLE
No Images

### ISSUE THREAD

**Issue by Saakshaat** [UMassACM/website#21]
There are zero images on the website. This probably has something to do with missing files in the CPanel.

**Comment by itsGovindC** [comment]
https://stackoverflow.com/questions/34582405/react-wont-load-local-images
https://stackoverflow.com/questions/39999367/how-do-i-reference-a-local-image-in-react

**Comment by itsGovindC** [comment]
Check these links out

**Comment by benjaminxu251** [comment]
solved by govind; imported directories as objects (iirc)
