### ISSUE TITLE
Add Navbar

### ISSUE THREAD

**Issue by Saakshaat** [UMassACM/website#29]
We want to add a nice and minimal navbar.

You'll want to add a navbar component in `components` and then import and use that component in the `GlobalLayout` in `components/layout` which will apply it globally.

Our  focus should be on making this minimal and accessible. Having a collapsible bar would be valuable.

**Comment by itsGovindC** [comment]
Added the navbar through recents commits on my branch. Will however transition to mobile/menu navbar.
