### ISSUE TITLE
Fix Social Icons

### ISSUE THREAD

**Issue by Saakshaat** [UMassACM/website#3]
Our Social icons at the bottom of the page look hideous. 
Think about having logos, instead of their names. 
Also implement them accounting for responsiveness and theme.

**Comment by benjaminxu251** [comment]
figure out how to replace chain-link image with discord and slack icons

**Comment by Saakshaat** [comment]
Just get their SVGs or PNGs from any open sourced logo website.

**Comment by benjaminxu251** [comment]
Asked customer support for SquareSpace about adding custom icons for Discord and Slack

> Are there any alternatives? If I manually upload the icons individually as images, they will take up the width of the device screen on mobile view.

Sebastian F.
> There wouldn't currently be any alternatives, unfortunately. That said, the issue you are referencing is definitely something that I hear fairly often—especially in relation to the mobile appearance—so I will be sure to add your particular site to the case.

This sounds like a common issue.
A proposed alternative was to have all four icons in one image, but then we can only link to one area, which defeats the purpose.

**Comment by benjaminxu251** [comment]
switching to hyperlinks at some point in the future

**Comment by benjaminxu251** [comment]
currently as words because:
-no way to integrate discord and slack icons into social links
-using images will make the mobile view very scuffed
