### ISSUE TITLE
Leadership Section

### ISSUE THREAD

**Issue by Saakshaat** [UMassACM/website#4]
Implement the layout of the leadership section. 

These are the things you need to consider:

- How are you going to implement the rows (for each Group) in Desktop and Phone Layout
- How are you going to implement the pop up description
- How are you going to display each card (each leader's)
- How are you going to theme the entire section
- Think about responsiveness for the entire and individual elements

**Comment by benjaminxu251** [comment]
not sure if it's possible to make the responsive design good for mobile
options: long ass scroll gallery vs SIG leadership on each SIG page

**Comment by benjaminxu251** [comment]
Done (just need the info)

**Comment by benjaminxu251** [comment]
add filler before actual info is recieved
